package ReykilLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TitleRender_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<h1>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$_Bdg));
    tgs.append("</h1>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty title$_Bdg = MetaAdapterFactory.getProperty(0x3ba2139d18a14caaL, 0x99b1d518013c442fL, 0x2d9e4360eb010b74L, 0x2d9e4360eb010b88L, "title");
  }
}
