package ReykillLanguageJSON.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptJSONReykill = createDescriptorForJSONReykill();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x3ba2139d18a14caaL, 0x99b1d518013c442fL, "ReykilLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptJSONReykill);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.JSONReykill:
        return myConceptJSONReykill;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForJSONReykill() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ReykillLanguageJSON", "JSONReykill", 0x7eb8d2096d8744aaL, 0x948aad64e7281f88L, 0x2d9e4360eb2a2865L);
    b.class_(false, false, true);
    // extends: ReykilLanguage.structure.ReykillDSL
    b.super_(0x3ba2139d18a14caaL, 0x99b1d518013c442fL, 0x64d22d80fe48070dL);
    b.origin("r:4347da0c-2208-4074-8209-1ce4b06368fc(ReykillLanguageJSON.structure)/3287138861568370789");
    b.version(3);
    return b.create();
  }
}
