MyDsl ::=
    Title
    Description
    Host
    Port
    'theme' '=' Theme
    'layout' '=' Layout
    'api' '=' Api
    'pages' '=' Pages
    'components' '=' Components

Description ::= 'description' '=' string
Host ::= 'host' '=' string
Port ::= 'port' '=' string

Theme ::= '{' 
    Mode?
    PColor?
    SColor?
    PBColor?
    SBColor?
    WBColor?
    EBColor?
'}'

Mode ::= 'mode' '=' ModeOpts
ModeOpts ::= dark | light
PColor ::= string
SColor ::= string
PBColor ::= string
SBColor ::= string
WBColor ::= string
EBColor ::= string

Layout ::= '{' 
    ShowMenu?
    ShowHeader?
    ShowFooter?
'}'
ShowMenu ::= 'showMenu' '=' boolean
ShowHeader ::= 'showHeader' '=' boolean
ShowFooter ::= 'showFooter' '=' boolean

Api ::= '{' 
    Base
    Endpoints
'}'
Base ::= 'base' '=' string
Endpoints ::= '{' 
    Get
    Post
'}'
Get ::= 'get' '=' '{' 
    LostItemsApi
    FoundItemsApi
    ProfileApi
'}'
Post ::= 'post' '=' '{' 
    ReportLostApi
    ReportFoundApi
    LoginApi
    RegisterApi
'}'
LostItemsApi ::= 'lostItems' '=' string
FoundItemsApi ::= 'foundItems' '=' string
ProfileApi ::= 'profile' '=' string
ReportLostApi ::= 'reportLost' '=' string
ReportFoundApi ::= 'reportFound' '=' string
LoginApi ::= 'login' '=' string
RegisterApi ::= 'register' '=' string

Pages ::= '{' 
    Home
    LostItems?
    FoundItems?
    ReportLost?
    ReportFound?
    About?
'}'
Home ::= 'Home' '=' '{' 
    Url
    Title
    Content
    QuickLinks
'}'
Title ::= 'title' '=' string
Content ::= 'content' '=' string
QuickLinks ::= '{' 
    View
    Links
'}'
View ::= 'view' '=' ViewOpts
ViewOpts ::= grid | list
Links ::= 'links' '=' '{' 
    ReportLostItem?
    ReportFoundItem?
    ListLostItem?
    ListFoundItem?
'}'
ReportLostItem ::= 'ReportLostItem' '=' '{' 
    Link
    Text
'}'
ReportFoundItem ::= 'ReportFoundItem' '=' '{' 
    Link
    Text
'}'
ListLostItem ::= 'ListLostItem' '=' '{' 
    Link
    Text
'}'
ListFoundItem ::= 'ListFoundItem' '=' '{' 
    Link
    Text
'}'

LostItems ::= 'LostItems' '=' '{' 
    Header
    Url
    Data
    View
'}'
FoundItems ::= 'FoundItems' '=' '{' 
    Header
    Url
    Data
    View
'}'

Header ::= 'header' '=' string
Url ::= 'url' '=' string
Data ::= 'data' '=' string
View ::= 'view' '=' ViewOpts






