package LAFLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import LAFLang.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.AppDescription:
        return new AppDescription_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.AppDescription$6F)) {
        String fname = getFileName_AppDescription(root);
        String ext = getFileExtension_AppDescription(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), getPath_AppDescription(root), root);
        continue;
      }
    }
  }
  private static String getFileName_AppDescription(SNode node) {
    return SPropertyOperations.getString(node, PROPS.name$MnvL);
  }
  private static String getFileExtension_AppDescription(SNode node) {
    return "ts";
  }
  private static String getPath_AppDescription(SNode node) {
    return "myApp/";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AppDescription$6F = MetaAdapterFactory.getConcept(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x1cb5501e1f91b6dcL, "LAFLang.structure.AppDescription");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
