package ReykilLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ComponentRender_SubstituteMenu extends SubstituteMenuBase {
  public ComponentRender_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for ComponentRender. Generated from implicit smart reference attribute.", new SNodePointer("r:23b57042-d6ed-4f0d-89db-f3550266e027(ReykilLanguage.structure)", "1180691636451029919")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_dblbma_a(), CONCEPTS.ComponentRender$1X));
    result.add(new SMP_Subconcepts_dblbma_b());
    return result;
  }

  public class SMP_ReferenceScope_dblbma_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_dblbma_a() {
      super(CONCEPTS.ComponentRender$1X, LINKS.cName$vz6U, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_dblbma_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_dblbma_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "ComponentRender", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.ComponentRender$1X);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ComponentRender$1X = MetaAdapterFactory.getConcept(0x3ba2139d18a14caaL, 0x99b1d518013c442fL, 0x1062a8c9abf0339fL, "ReykilLanguage.structure.ComponentRender");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink cName$vz6U = MetaAdapterFactory.getReferenceLink(0x3ba2139d18a14caaL, 0x99b1d518013c442fL, 0x1062a8c9abf0339fL, 0x2d9e4360eb0b12a2L, "cName");
  }
}
