package ReykilLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ComponentRender = 0;
  public static final int IElementRender = 1;
  public static final int ParagraphRender = 2;
  public static final int RApi = 3;
  public static final int RComponent = 4;
  public static final int REndPoint = 5;
  public static final int ReykillDSL = 6;
  public static final int TitleRender = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3ba2139d18a14caaL, 0x99b1d518013c442fL);
    builder.put(0x1062a8c9abf0339fL, ComponentRender);
    builder.put(0x2d9e4360eafebf2eL, IElementRender);
    builder.put(0x2d9e4360eafebf33L, ParagraphRender);
    builder.put(0x64d22d80fe4b4a9bL, RApi);
    builder.put(0x64d22d80fe48072aL, RComponent);
    builder.put(0x64d22d80fe4b4aa1L, REndPoint);
    builder.put(0x64d22d80fe48070dL, ReykillDSL);
    builder.put(0x2d9e4360eb010b74L, TitleRender);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
