package LAFLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ViewEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ViewEnum() {
    super(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e0026L, "ViewEnum", "r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829297190");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_grid_0 = new EnumerationDescriptor.MemberDescriptor("grid", "grid", 0x33d2680e563e0027L, "r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829297191");
  private final EnumerationDescriptor.MemberDescriptor myMember_list_0 = new EnumerationDescriptor.MemberDescriptor("list", "list", 0x33d2680e563e0028L, "r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829297192");
  private final EnumerationDescriptor.MemberDescriptor myMember_table_0 = new EnumerationDescriptor.MemberDescriptor("table", "table", 0x33d2680e563e0029L, "r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829297193");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e0026L, 0x33d2680e563e0027L, 0x33d2680e563e0028L, 0x33d2680e563e0029L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_grid_0, myMember_list_0, myMember_table_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_grid_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "grid":
        return myMember_grid_0;
      case "list":
        return myMember_list_0;
      case "table":
        return myMember_table_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
