package LAFLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int About = 0;
  public static final int Api = 1;
  public static final int ApiGet = 2;
  public static final int ApiPost = 3;
  public static final int AppDescription = 4;
  public static final int Components = 5;
  public static final int Endpoints = 6;
  public static final int FoundItems = 7;
  public static final int Home = 8;
  public static final int Layout = 9;
  public static final int Links = 10;
  public static final int ListFoundLink = 11;
  public static final int ListLostLink = 12;
  public static final int LostItems = 13;
  public static final int Pages = 14;
  public static final int QuickLinks = 15;
  public static final int ReportFound = 16;
  public static final int ReportFoundLink = 17;
  public static final int ReportLost = 18;
  public static final int ReportLostLink = 19;
  public static final int Theme = 20;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L);
    builder.put(0x33d2680e563a10c2L, About);
    builder.put(0x33d2680e5629c05fL, Api);
    builder.put(0x33d2680e5629c062L, ApiGet);
    builder.put(0x33d2680e5629c066L, ApiPost);
    builder.put(0x1cb5501e1f91b6dcL, AppDescription);
    builder.put(0x33d2680e56342a8eL, Components);
    builder.put(0x33d2680e5629c0e1L, Endpoints);
    builder.put(0x33d2680e563a10bfL, FoundItems);
    builder.put(0x33d2680e5637b051L, Home);
    builder.put(0x33d2680e5626a39eL, Layout);
    builder.put(0x33d2680e563e002dL, Links);
    builder.put(0x33d2680e5640e43eL, ListFoundLink);
    builder.put(0x33d2680e5640e43dL, ListLostLink);
    builder.put(0x33d2680e563a10beL, LostItems);
    builder.put(0x33d2680e5631d7a0L, Pages);
    builder.put(0x33d2680e563c973bL, QuickLinks);
    builder.put(0x33d2680e563a10c1L, ReportFound);
    builder.put(0x33d2680e5640e43cL, ReportFoundLink);
    builder.put(0x33d2680e563a10c0L, ReportLost);
    builder.put(0x33d2680e5640e434L, ReportLostLink);
    builder.put(0x33d2680e5616bba7L, Theme);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
