package LAFLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAbout = createDescriptorForAbout();
  /*package*/ final ConceptDescriptor myConceptApi = createDescriptorForApi();
  /*package*/ final ConceptDescriptor myConceptApiGet = createDescriptorForApiGet();
  /*package*/ final ConceptDescriptor myConceptApiPost = createDescriptorForApiPost();
  /*package*/ final ConceptDescriptor myConceptAppDescription = createDescriptorForAppDescription();
  /*package*/ final ConceptDescriptor myConceptComponents = createDescriptorForComponents();
  /*package*/ final ConceptDescriptor myConceptEndpoints = createDescriptorForEndpoints();
  /*package*/ final ConceptDescriptor myConceptFoundItems = createDescriptorForFoundItems();
  /*package*/ final ConceptDescriptor myConceptHome = createDescriptorForHome();
  /*package*/ final ConceptDescriptor myConceptLayout = createDescriptorForLayout();
  /*package*/ final ConceptDescriptor myConceptLinks = createDescriptorForLinks();
  /*package*/ final ConceptDescriptor myConceptListFoundLink = createDescriptorForListFoundLink();
  /*package*/ final ConceptDescriptor myConceptListLostLink = createDescriptorForListLostLink();
  /*package*/ final ConceptDescriptor myConceptLostItems = createDescriptorForLostItems();
  /*package*/ final ConceptDescriptor myConceptPages = createDescriptorForPages();
  /*package*/ final ConceptDescriptor myConceptQuickLinks = createDescriptorForQuickLinks();
  /*package*/ final ConceptDescriptor myConceptReportFound = createDescriptorForReportFound();
  /*package*/ final ConceptDescriptor myConceptReportFoundLink = createDescriptorForReportFoundLink();
  /*package*/ final ConceptDescriptor myConceptReportLost = createDescriptorForReportLost();
  /*package*/ final ConceptDescriptor myConceptReportLostLink = createDescriptorForReportLostLink();
  /*package*/ final ConceptDescriptor myConceptTheme = createDescriptorForTheme();
  /*package*/ final EnumerationDescriptor myEnumerationMode = new EnumerationDescriptor_Mode();
  /*package*/ final EnumerationDescriptor myEnumerationViewEnum = new EnumerationDescriptor_ViewEnum();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAbout, myConceptApi, myConceptApiGet, myConceptApiPost, myConceptAppDescription, myConceptComponents, myConceptEndpoints, myConceptFoundItems, myConceptHome, myConceptLayout, myConceptLinks, myConceptListFoundLink, myConceptListLostLink, myConceptLostItems, myConceptPages, myConceptQuickLinks, myConceptReportFound, myConceptReportFoundLink, myConceptReportLost, myConceptReportLostLink, myConceptTheme);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.About:
        return myConceptAbout;
      case LanguageConceptSwitch.Api:
        return myConceptApi;
      case LanguageConceptSwitch.ApiGet:
        return myConceptApiGet;
      case LanguageConceptSwitch.ApiPost:
        return myConceptApiPost;
      case LanguageConceptSwitch.AppDescription:
        return myConceptAppDescription;
      case LanguageConceptSwitch.Components:
        return myConceptComponents;
      case LanguageConceptSwitch.Endpoints:
        return myConceptEndpoints;
      case LanguageConceptSwitch.FoundItems:
        return myConceptFoundItems;
      case LanguageConceptSwitch.Home:
        return myConceptHome;
      case LanguageConceptSwitch.Layout:
        return myConceptLayout;
      case LanguageConceptSwitch.Links:
        return myConceptLinks;
      case LanguageConceptSwitch.ListFoundLink:
        return myConceptListFoundLink;
      case LanguageConceptSwitch.ListLostLink:
        return myConceptListLostLink;
      case LanguageConceptSwitch.LostItems:
        return myConceptLostItems;
      case LanguageConceptSwitch.Pages:
        return myConceptPages;
      case LanguageConceptSwitch.QuickLinks:
        return myConceptQuickLinks;
      case LanguageConceptSwitch.ReportFound:
        return myConceptReportFound;
      case LanguageConceptSwitch.ReportFoundLink:
        return myConceptReportFoundLink;
      case LanguageConceptSwitch.ReportLost:
        return myConceptReportLost;
      case LanguageConceptSwitch.ReportLostLink:
        return myConceptReportLostLink;
      case LanguageConceptSwitch.Theme:
        return myConceptTheme;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationMode, myEnumerationViewEnum);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAbout() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "About", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c2L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829039298");
    b.version(3);
    b.property("url", 0x33d2680e564df481L).type(PrimitiveTypeId.STRING).origin("3734161451830342785").done();
    b.property("title", 0x33d2680e564df483L).type(PrimitiveTypeId.STRING).origin("3734161451830342787").done();
    b.property("content", 0x33d2680e564df484L).type(PrimitiveTypeId.STRING).origin("3734161451830342788").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Api", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c05fL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451827970143");
    b.version(3);
    b.property("base", 0x33d2680e5629c061L).type(PrimitiveTypeId.STRING).origin("3734161451827970145").done();
    b.aggregate("endpoints", 0x33d2680e5629c0e6L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c0e1L).optional(false).ordered(true).multiple(false).origin("3734161451827970278").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApiGet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ApiGet", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c062L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451827970146");
    b.version(3);
    b.property("lostItems", 0x33d2680e5629c063L).type(PrimitiveTypeId.STRING).origin("3734161451827970147").done();
    b.property("foundItems", 0x33d2680e5629c064L).type(PrimitiveTypeId.STRING).origin("3734161451827970148").done();
    b.property("profile", 0x33d2680e5629c065L).type(PrimitiveTypeId.STRING).origin("3734161451827970149").done();
    b.aggregate("layout", 0x33d2680e5637b039L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5626a39eL).optional(true).ordered(true).multiple(false).origin("3734161451828883513").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApiPost() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ApiPost", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c066L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451827970150");
    b.version(3);
    b.property("reportLost", 0x33d2680e5629c067L).type(PrimitiveTypeId.STRING).origin("3734161451827970151").done();
    b.property("reportFound", 0x33d2680e5629c068L).type(PrimitiveTypeId.STRING).origin("3734161451827970152").done();
    b.property("login", 0x33d2680e5629c069L).type(PrimitiveTypeId.STRING).origin("3734161451827970153").done();
    b.property("register", 0x33d2680e5629c06aL).type(PrimitiveTypeId.STRING).origin("3734161451827970154").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAppDescription() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "AppDescription", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x1cb5501e1f91b6dcL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/2068647694155495132");
    b.version(3);
    b.property("title", 0x1cb5501e1f91c020L).type(PrimitiveTypeId.STRING).origin("2068647694155497504").done();
    b.property("description", 0x1cb5501e1f91c026L).type(PrimitiveTypeId.STRING).origin("2068647694155497510").done();
    b.property("host", 0x1cb5501e1f91c023L).type(PrimitiveTypeId.STRING).origin("2068647694155497507").done();
    b.property("port", 0x1cb5501e1f9282a8L).type(PrimitiveTypeId.INTEGER).origin("2068647694155547304").done();
    b.aggregate("theme", 0x33d2680e5616bbbfL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5616bba7L).optional(false).ordered(true).multiple(false).origin("3734161451826723775").done();
    b.aggregate("layout", 0x33d2680e5626a3a5L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5626a39eL).optional(false).ordered(true).multiple(false).origin("3734161451827766181").done();
    b.aggregate("api", 0x33d2680e562aeae1L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c05fL).optional(false).ordered(true).multiple(false).origin("3734161451828046561").done();
    b.aggregate("pages", 0x33d2680e5631d7dfL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5631d7a0L).optional(false).ordered(true).multiple(false).origin("3734161451828500447").done();
    b.aggregate("components", 0x33d2680e563556b6L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e56342a8eL).optional(false).ordered(true).multiple(false).origin("3734161451828729526").done();
    b.alias("appDescription");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponents() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Components", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e56342a8eL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451828652686");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEndpoints() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Endpoints", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c0e1L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451827970273");
    b.version(3);
    b.aggregate("get", 0x33d2680e5629c0e2L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c062L).optional(false).ordered(true).multiple(false).origin("3734161451827970274").done();
    b.aggregate("post", 0x33d2680e5629c0e3L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5629c066L).optional(false).ordered(true).multiple(false).origin("3734161451827970275").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFoundItems() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "FoundItems", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10bfL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829039295");
    b.version(3);
    b.property("header", 0x33d2680e56467245L).type(PrimitiveTypeId.STRING).origin("3734161451829850693").done();
    b.property("url", 0x33d2680e56467246L).type(PrimitiveTypeId.STRING).origin("3734161451829850694").done();
    b.property("description", 0x33d2680e56467247L).type(PrimitiveTypeId.STRING).origin("3734161451829850695").done();
    b.property("data", 0x33d2680e56467248L).type(PrimitiveTypeId.STRING).origin("3734161451829850696").done();
    b.property("view", 0x33d2680e56467249L).type(MetaIdFactory.dataTypeId(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e0026L)).origin("3734161451829850697").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHome() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Home", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5637b051L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451828883537");
    b.version(3);
    b.property("url", 0x33d2680e563c9719L).type(PrimitiveTypeId.STRING).origin("3734161451829204761").done();
    b.property("title", 0x33d2680e563c971aL).type(PrimitiveTypeId.STRING).origin("3734161451829204762").done();
    b.property("content", 0x33d2680e563c971bL).type(PrimitiveTypeId.STRING).origin("3734161451829204763").done();
    b.aggregate("quickLinks", 0x33d2680e563c9762L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563c973bL).optional(true).ordered(true).multiple(false).origin("3734161451829204834").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayout() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Layout", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5626a39eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f1e14d895L);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451827766174");
    b.version(3);
    b.property("showMenu", 0x33d2680e5626a3a0L).type(PrimitiveTypeId.BOOLEAN).origin("3734161451827766176").done();
    b.property("showHeader", 0x33d2680e5626a3a1L).type(PrimitiveTypeId.BOOLEAN).origin("3734161451827766177").done();
    b.property("showFooter", 0x33d2680e5626a3a3L).type(PrimitiveTypeId.BOOLEAN).origin("3734161451827766179").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinks() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Links", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e002dL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829297197");
    b.version(3);
    b.aggregate("reportLostItem", 0x33d2680e5640e4c4L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e434L).optional(true).ordered(true).multiple(false).origin("3734161451829486788").done();
    b.aggregate("reportFoundItem", 0x33d2680e5640e4c5L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43cL).optional(true).ordered(true).multiple(false).origin("3734161451829486789").done();
    b.aggregate("listLostItem", 0x33d2680e5640e4c6L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43dL).optional(true).ordered(true).multiple(false).origin("3734161451829486790").done();
    b.aggregate("listFoundItem", 0x33d2680e5640e4c7L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43eL).optional(true).ordered(true).multiple(false).origin("3734161451829486791").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListFoundLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ListFoundLink", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43eL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829486654");
    b.version(3);
    b.property("link", 0x33d2680e56426c00L).type(PrimitiveTypeId.STRING).origin("3734161451829586944").done();
    b.property("text", 0x33d2680e56426c01L).type(PrimitiveTypeId.STRING).origin("3734161451829586945").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListLostLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ListLostLink", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43dL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829486653");
    b.version(3);
    b.property("link", 0x33d2680e56426bf0L).type(PrimitiveTypeId.STRING).origin("3734161451829586928").done();
    b.property("text", 0x33d2680e56426bf1L).type(PrimitiveTypeId.STRING).origin("3734161451829586929").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLostItems() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "LostItems", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10beL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829039294");
    b.version(3);
    b.property("header", 0x33d2680e56445125L).type(PrimitiveTypeId.STRING).origin("3734161451829711141").done();
    b.property("url", 0x33d2680e56445126L).type(PrimitiveTypeId.STRING).origin("3734161451829711142").done();
    b.property("description", 0x33d2680e56445127L).type(PrimitiveTypeId.STRING).origin("3734161451829711143").done();
    b.property("data", 0x33d2680e56445129L).type(PrimitiveTypeId.STRING).origin("3734161451829711145").done();
    b.property("view", 0x33d2680e5644512aL).type(MetaIdFactory.dataTypeId(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e0026L)).origin("3734161451829711146").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPages() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Pages", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5631d7a0L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451828500384");
    b.version(3);
    b.aggregate("Home", 0x33d2680e5637b06bL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5637b051L).optional(false).ordered(true).multiple(false).origin("3734161451828883563").done();
    b.aggregate("LostItems", 0x33d2680e563a112cL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10beL).optional(true).ordered(true).multiple(false).origin("3734161451829039404").done();
    b.aggregate("FoundItems", 0x33d2680e563a112dL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10bfL).optional(true).ordered(true).multiple(false).origin("3734161451829039405").done();
    b.aggregate("ReportLost", 0x33d2680e563a112eL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c0L).optional(true).ordered(true).multiple(false).origin("3734161451829039406").done();
    b.aggregate("ReportFound", 0x33d2680e563a112fL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c1L).optional(true).ordered(true).multiple(false).origin("3734161451829039407").done();
    b.aggregate("About", 0x33d2680e563a1130L).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c2L).optional(true).ordered(true).multiple(false).origin("3734161451829039408").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuickLinks() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "QuickLinks", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563c973bL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829204795");
    b.version(3);
    b.property("view", 0x33d2680e563e002bL).type(MetaIdFactory.dataTypeId(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e0026L)).origin("3734161451829297195").done();
    b.aggregate("links", 0x33d2680e563e004aL).target(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563e002dL).optional(false).ordered(true).multiple(false).origin("3734161451829297226").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReportFound() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ReportFound", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c1L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829039297");
    b.version(3);
    b.property("url", 0x33d2680e5648cf2cL).type(PrimitiveTypeId.STRING).origin("3734161451830005548").done();
    b.property("post", 0x33d2680e5648cf2dL).type(PrimitiveTypeId.STRING).origin("3734161451830005549").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReportFoundLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ReportFoundLink", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e43cL);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829486652");
    b.version(3);
    b.property("link", 0x33d2680e56426bedL).type(PrimitiveTypeId.STRING).origin("3734161451829586925").done();
    b.property("text", 0x33d2680e56426beeL).type(PrimitiveTypeId.STRING).origin("3734161451829586926").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReportLost() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ReportLost", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e563a10c0L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829039296");
    b.version(3);
    b.property("url", 0x33d2680e5648cf2aL).type(PrimitiveTypeId.STRING).origin("3734161451830005546").done();
    b.property("post", 0x33d2680e5648cf2bL).type(PrimitiveTypeId.STRING).origin("3734161451830005547").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReportLostLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "ReportLostLink", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5640e434L);
    b.class_(false, false, false);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451829486644");
    b.version(3);
    b.property("link", 0x33d2680e5640e438L).type(PrimitiveTypeId.STRING).origin("3734161451829486648").done();
    b.property("text", 0x33d2680e5640e43aL).type(PrimitiveTypeId.STRING).origin("3734161451829486650").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTheme() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LAFLang", "Theme", 0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5616bba7L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b1a94a14-22d3-46bf-a434-442a7523a97d(LAFLang.structure)/3734161451826723751");
    b.version(3);
    b.property("mode", 0x33d2680e5616bbacL).type(MetaIdFactory.dataTypeId(0xb82b0909bdfe46caL, 0xb9021bba8a0c6791L, 0x33d2680e5616bbadL)).origin("3734161451826723756").done();
    b.property("primary_color", 0x33d2680e5616bbb7L).type(PrimitiveTypeId.STRING).origin("3734161451826723767").done();
    b.property("secondary_color", 0x33d2680e5616bbb2L).type(PrimitiveTypeId.STRING).origin("3734161451826723762").done();
    b.property("primary_btn_color", 0x33d2680e5616bbb8L).type(PrimitiveTypeId.STRING).origin("3734161451826723768").done();
    b.property("secondary_btn_color", 0x33d2680e5616bbb9L).type(PrimitiveTypeId.STRING).origin("3734161451826723769").done();
    b.property("warning_btn_color", 0x33d2680e5616bbbaL).type(PrimitiveTypeId.STRING).origin("3734161451826723770").done();
    b.property("error_btn_color", 0x33d2680e5616bbbcL).type(PrimitiveTypeId.STRING).origin("3734161451826723772").done();
    return b.create();
  }
}
