export const CATEGORIES = [
    'Electronics',
    'Clothing',
    'Documents',
    'Accessories',
    'Jewelry',
    'Books',
    'Keys',
    'Wallets',
    'Bags',
    'Sports Equipment',
    'Toys',
    'Tools',
    'Footwear',
    'Home Goods',
    'Other'
];
export const LOCATIONS = [
    'Ljubljana',
    'Maribor',
    'Celje',
    'Kranj',
    'Velenje',
    'Koper',
    'Novo Mesto',
    'Ptuj',
    'Trbovlje',
    'Kamnik',
    'Jesenice',
    'Izola',
    'Domžale',
    'Škofja Loka',
    'Murska Sobota',
    'Nova Gorica',
    'Slovenj Gradec',
    'Ravne na Koroškem',
    'Piran',
    'Sežana',
    'Idrija',
    'Radovljica',
    'Slovenska Bistrica',
    'Brežice',
    'Postojna',
    'Tolmin',
    'Ajdovščina',
    'Litija',
    'Črnomelj',
    'Vrhnika',
    'Ljutomer',
    'Metlika',
    'Rogaška Slatina',
    'Laško',
    'Gornja Radgona',
    'Šentjur',
    'Ilirska Bistrica',
    'Kočevje',
    'Bled',
    'Vipava',
    'Žalec',
    'Hrastnik',
    'Ribnica',
    'Preddvor',
    'Portorož',
    'Šoštanj',
    'Radenci',
    'Cerknica',
    'Ormož',
    'Turnišče',
    'Šmarje pri Jelšah',
    'Moravče',
    'Dravograd',
    'Planina',
    'Polhov Gradec',
    'Kobarid',
    'Divača',
    'Logatec',
    'Ankaran',
    'Žiri',
    'Črna na Koroškem',
    'Lovrenc na Pohorju',
    'Kidričevo',
    'Destrnik',
    'Bohinj',
    'Borovnica',
    'Komenda',
    'Šentjernej',
    'Tržič',
    'Mirna',
    'Velika Polana'
];
